name: Lua Script Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Lua
      uses: ByteXenon/gh-actions-lua
      with:
        luaVersion: "5.4.0"

    - name: Run script
      run: |
        bash tests/test.sh 
